# An example configuration file for Projection. Here we lay out our custom
# syntax as well as some meta-information

meta:
  title: "Hello World"
  author: "Author"
  database: "example.db"


sections:
  - name: "Notes"
    syntax: "section"
    level: 0
  - name: "Lectures"
    syntax: "lecture"
    level: 2


collectors:
  - name: "Keypoints"
    syntax: "keypoint"
  - name: "Questions"
    syntax: "question"


removals:
  - name: "PDFONLY"
    syntax:
      start: "beginpdfonly"
      end: "endpdfonly"


# Here we define our pages that are not the ones defined by 'breaks'

pages:
  - name: "Glossary"
    type: "glossary"
  - name: "Interactive"
    type: "subpages"
  - name: "Plain"
    type: "plain"



