# An example configuration file for Projection. Here we lay out our custom
# syntax as well as some meta-information

meta:
  title: "Hello World"
  author: "Author"


breaks:
  - name: "Notes"
    syntax: "section"
  - name: "Lectures"
    syntax: "lecture"


collectors:
  - name: "Keypoints"
    sytnax: "keypoint"
  - name: "Questions"
    syntax: "question"


# Here we define our pages that are not the ones defined by 'breaks'

pages:
  - name: "Glossary"
    type: "glossary"
  - name: "Interactive"
    type: "subpages"
  - name: "Plain"
    type: "plain"



